### ISSUE TITLE
 GLib.spawn_sync stop the cinnamon compositor thread until the function return a value

### ISSUE THREAD

**Issue by ghost** [linux-man/cinnamon-printers#2]
Please don't use  GLib.spawn_sync, instead you can use https://github.com/linuxmint/Cinnamon/blob/master/js/misc/util.js#L81

As this execute the spaw outside of cinnamon compositor thread and you will not stop the only one thread that cinnamon have waiting for the result of your command.

Alternatively, you can use GLib.spawn_async_with_pipes. Here you can find an example:
https://github.com/lestcape/Configurable-Menu/blob/master/configurableMenu%40lestcape/pakagesManager.js#L35

**Comment by linux-man** [comment]
I moved to Util.spawn_async. Once again, the main problem is the lack of documentation (and the apparently insane work to use async calls). Finally I found the spawn_async callback parameters on one of your posts. Thanks for pushing me further.

**Comment by ghost** [comment]
I known this is one of the most difficult things, because this is not an error on your code or something similar... This is only relate with the architecture of cinnamon and for a thing like that we don't have documentation. Feel free to propose or create one if you can... I'm a simpler user and fan of cinnamon, not more than that.

**Comment by ghost** [comment]
I found your extension in this thread: https://github.com/linuxmint/Cinnamon/issues/2476
