### ISSUE TITLE
Show icons option

### ISSUE THREAD

**Issue by NikoKrause** [linux-man/cinnamon-printers#3]
Can you make another option "Show icon only, when a printer is connected to your laptop/PC"

So you can use a combobox instead of a checkbox/switcher, with the options:
1. Always show icon 
2. Show icon only when printer is connected
3. Show icon only when printing

**Comment by linux-man** [comment]
I guess you are talking about connected local printers (on opposition to installed but disconnected).
Since I mostly use network printers I must do some tests.
I don't know if this option is very useful - an installed PDF or Network printer will make it useless.

**Comment by NikoKrause** [comment]
Yes. I use a laptop with USB printer. If the printer is not connected with the laptop, left mouse click on applet icon does nothing. Maybe as an alternative you could make the menu pop up and show a notification "No printer connected"?

**Comment by linux-man** [comment]
My mistake. The applet should always show a link to "system-config-printer". When I changed to async calls I didn't test for no printers installed, and spawn_async kind of breaks with a null output.
Please try the new version and tell me if you still prefer the "Show icon only when printer is connected" option.

**Comment by NikoKrause** [comment]
Yes, that's better. Then the other option is not needed.

Could you add this to the po files?
```
#. printers@linux-man->metadata.json->description
msgid "Manage Jobs and Printers"
msgstr ""
```

**Comment by linux-man** [comment]
OK. One more update - hope that everything is back to normal.

**Comment by NikoKrause** [comment]
I forgot to tell you the german translation:
```
#. printers@linux-man->metadata.json->description
msgid "Manage Jobs and Printers"
msgstr "Druckaufträge und Drucker verwalten"
```

**Comment by linux-man** [comment]
I decided to implement your idea. Can you please confirm the translation?

**Comment by NikoKrause** [comment]
msgid "Show icon"
msgstr "Symbol anzeigen"

The rest looks good to me.

**Comment by linux-man** [comment]
Thanks.
